### ISSUE TITLE
Ask some questions

### ISSUE THREAD

**Issue by coderookieqi** [EPFL-VILAB/XDEnsembles#1]
Hello author, I am a postgraduate student from Tsinghua University in China. The master's research topic is environmental perception in autonomous driving. I have closely read your article "Rapid Network Adaptation: Learning to Adapt Neural Networks Using Test-Time Feedback". I've had the same idea as you before, designing a corrective network to adapt the original network to the new data set. I would like to ask when your code will be open source? Or I have some ideas on this subject. Can we exchange them? My Google Email is: szqi2023@gmail.com

**Comment by aserety** [comment]
Hi! We will release our code in about 2 weeks. Sorry for the delay! Yes of course, we can exchange ideas, I will send you an email.
